### ISSUE TITLE
Chat page improvements

### ISSUE THREAD

**Issue by ochnios** [ochnios/samurai#39]
- [x] #9 Chat input needs to be multiline
- [x] #17 Markdown formatting in chat messages
- [x] #20  Summary of started conversation is not highlighted

... and other
